
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T01:14:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "297def36284a889dc455dfab153231eed226549c",
 "version": "0.2.50.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
