# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/truera_custom_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2truera/protobuf/public/truera_custom_options.proto\x12\x06truera\x1a google/protobuf/descriptor.proto:J\n\"truera_restrict_add_fields_in_file\x12\x1c.google.protobuf.FileOptions\x18\xa2\x90\x03 \x01(\x08:L\n!truera_restrict_add_message_field\x12\x1f.google.protobuf.MessageOptions\x18\xa3\x90\x03 \x01(\x08\x62\x06proto3')


TRUERA_RESTRICT_ADD_FIELDS_IN_FILE_FIELD_NUMBER = 51234
truera_restrict_add_fields_in_file = DESCRIPTOR.extensions_by_name['truera_restrict_add_fields_in_file']
TRUERA_RESTRICT_ADD_MESSAGE_FIELD_FIELD_NUMBER = 51235
truera_restrict_add_message_field = DESCRIPTOR.extensions_by_name['truera_restrict_add_message_field']

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(truera_restrict_add_fields_in_file)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(truera_restrict_add_message_field)

  DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
