# Generated by Django 4.1.3 on 2022-11-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jangle", "0002_rename_ext_data_regionsubtag_region"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ianasubtagdescription",
            unique_together={("subtag", "index")},
        ),
        migrations.AlterField(
            model_name="ianasubtagdescription",
            name="text",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="isolanguage",
            name="ref_name",
            field=models.CharField(
                max_length=150, verbose_name="reference name"
            ),
        ),
        migrations.AlterField(
            model_name="isolanguagecodes",
            name="names_en",
            field=models.CharField(
                max_length=254, unique=True, verbose_name="noms français"
            ),
        ),
        migrations.AlterField(
            model_name="isolanguagecodes",
            name="names_fr",
            field=models.CharField(
                max_length=254, unique=True, verbose_name="English names"
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="names_en",
            field=models.CharField(
                max_length=254, unique=True, verbose_name="English names"
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="names_fr",
            field=models.CharField(
                max_length=254, unique=True, verbose_name="noms français"
            ),
        ),
        migrations.AlterField(
            model_name="simpleisolanguagecollection",
            name="names_en",
            field=models.CharField(
                max_length=254, unique=True, verbose_name="English names"
            ),
        ),
        migrations.AlterField(
            model_name="simpleisolanguagecollection",
            name="names_fr",
            field=models.CharField(
                max_length=254, unique=True, verbose_name="noms français"
            ),
        ),
    ]
