
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-02T11:23:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea4031cad266c4fa30a7dfac00559c71f5dc9e8a",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
