
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/underpants:dist

from setuptools import setup

setup(**{
    'classifiers': [
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python',
        'Topic :: Software Development :: Libraries',
    ],
    'description': 'Leverage the Rules Engine from the Pants Build System as a library.',
    'install_requires': (
        'pantsbuild.pants<2.15,>=2.14.0a0',
    ),
    'license': 'MIT',
    'long_description': """
`underpants` - Or, using Pants as an embedded rules engine
==========================================================

For Pantsbuild version: 2.14.0

DISCLAIMER: This is not in any way to show how to use Pants, or recommended patterns of
use. Provided here AS-IS. No gurantees of any kind, as this may break with any future release of
Pants.

This is a toy POC testing out the feasability of using the [Pants Build
System](https://www.pantsbuild.org/) as a rule engine in your Python application.

The relative narrow Python interpreter constraint of 3.9.* is due to the combination of Pants ICs of
>=3.7,<3.10 and the fact that for ARM based Mac (M1s) only >=3.9 works with Pants.

""",
    'long_description_content_type': 'text/markdown',
    'name': 'underpants',
    'namespace_packages': (
    ),
    'package_data': {
        'underpants': (
            'py.typed',
        ),
    },
    'packages': (
        'underpants',
    ),
    'project_urls': {
        'Documentation': 'https://github.com/kaos/underpants/wiki',
        'Source': 'https://github.com/kaos/underpants',
        'Tracker': 'https://github.com/kaos/underpants/issues',
    },
    'python_requires': '<3.10,>=3.9',
    'version': '0.2.4',
})
