
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-03T11:23:34+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8cde903bf64090a4cdfee766699c1d16cf24d9c0",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
