import random

def add(num1, num2):
    return num1 + num2

def roll(num1, num2):
    return random.randint(num1, num2)

def lustig():
    return random.choice(lust)








lust = ['Alle Kinder trinken Limo, nur nicht Nils der trinkt Pils.',
'Sagt der Arzt zum Kleinkünstler: „Sie haben noch 6 Monate zu leben.“ – Darauf der Kleinkünstler: 6 Monate? So lange kann ich mir nicht leisten!“',
'Wissen Veganer eigentlich, dass sie in der Milchstraße leben?',
'Optimist: „Das Glas ist halb voll.“ – Pessimist: „Das Glas ist halb leer.“ – Mama: „Wieso ist da kein Untersetzer?“ Immer.',
'Merke: Man sollte im Altenheim kein „Last Christmas“ singen!',
'Was sind gemischte Gefühle? Wenn die Schwiegermutter rückwärts im neuen BWW auf eine Steilklippe zufährt.',
'„Dingdong. „Guten Tag, wir sammeln fürs Kinderheim. Haben Sie etwas abzugeben?“ – „Kevin, Justin – kommt mal her!“',
'Mein Freund hat mich kurzfristig zum Finale der Fußball Weltmeisterschaft eingeladen, er hat noch ein Ticket übrig. Leider heirate ich an diesem Tag. Wenn du jemanden kennst, der Interesse hat, sag bitte kurz Bescheid: Sie wartet vor der Gottlieb-Kirche, ist blond, 1,70 groß und heißt Stephanie.',
'Ein Malerlehrling soll die Markierungen auf der Autobahn erneuern. Am ersten Tag schafft er mehr als zwei Kilometer, am zweiten Tag nur noch 500 Meter, am dritten sogar nur noch 200 Meter. Fragt der Chef: „Warum schaffst du nicht mehr so viel wie am Anfang?“ Darauf der Lehrling: „Naja, der Weg zum Farbeimer ist inzwischen echt weit…“',
'„Wie viel wiegt deine Frau?“ – Frag mich bitte was Leichteres.',
'„Auf einer Skala von 1 bis 10, wie sehr haben Sie in Ihrer Beziehung die Hosen an?“ – „Schatz? Darf ich bitte an einer Umfrage teilnehmen?“',
'„Ich kuschele 2-3 Mal in der Woche mit meinem Mann.“ – „Ich meistens nur einmal.“ – „Aber du hast doch gar keinen Mann?“ – „Oh, ich dachte, wir reden über deinen Mann.“',
'„Ich würde ja gerne ein paar Kilos verlieren. Aber ich verliere nie. Ich bin ein Gewinner!“',
'„Siri, warum sind Frauen so komisch zu mir?“ – „Mein Name ist Alexa!“',
'Treffen sich 2 Eier: „Warum bist du so behaart?“ Darauf das andere: „Klappe! Ich bin eine Kiwi!“',
'Hast du ein Bad genommen? Warum, fehlt eins?',
'Egal, wie gut du schläfst: Albert schläft wie Einstein.',
'Egal, wie gut du fährst, Züge fahren Güter.',
'Was kommt nach Elch? Zwölch',
'Wissenschaftler haben herausgefunden und sind wieder reingegangen.',
'Habe gerade beim Brötchen angerufen… War belegt!',
'Abgemacht ist abgemacht! Klaus, 42, Chirurg',
'Habe meinen Mathelehrer angerufen… Damit hat er nicht gerechnet!',
'Was versteht man unter einer Turbine? Nichts ist viel zu laut!',
'Übrigens: ich habe gerade ein Blatt gelocht… Aber das nur am Rande.',
'Steht ein Baum allein im Wald.',
'Sitzt einer im Stehcafé.',
'Was macht man mit einem Hund ohne Beine? Um die Häuser ziehen.',
'Wie heisst der Schutzpatron der Vergesslichen? Dings',
'Was machen Mathematiker im Garten? Wurzeln ziehen',
'Wollte Spiderman anrufen, aber der hatte kein Netz.',
'In welchen Urlaubsort wird am meisten geflucht? Tourette de Mar',
'Wenn sich Wissenschaftler ein Brot belegt, ist es dann wissenschaftlich belegt?',
'Das Mathebuch ist der einzige Ort, wo es normal ist, 53 Melonen zu kaufen.',
'Weil es dann nicht mehr lustig ist. Warum sollte man die Pointe nie zuerst erzählen?',
'Was ist rot und schlecht für die Zähne? Ein Ziegelstein',
'Was ist die Mehrzahl von Rettich? Meerrettich',
'Was hat vier Beine und kann fliegen? Zwei Vögel',
'Ich stecke gerade in der Bredouille! Wie schön, Frankreich!',
'Was sagt ein Polizist mit sächsischem Dialekt? Ägyptisch oder ich schiesse.',
'Geht ein Neutron in die Disco. Sagt der Türsteher: Nur für geladene Gäste!',
'Wann gehen U-Boote unter? Am Tag der offenen Tür.',
'Was ist die Lieblingsspeise von Piraten? Kaper',
'Meiser Yoda, können Sie was zum schiefen Turm von Pisa sagen? Gerade nicht.',
'Warum klaut Robin Hood Deodorant? Um es unter den Armen zu verteilen',
'Meine Oma ist Griechin. Ach, Feta-licherseits?',
'Wie nennt man jemanden, der so tut, als würde er etwas werfen? Scheinwerfer',
'Treffen sich zwei Kerzen: Sagt die eine zur anderen: Gehen wir heute aus?',
'Was passiert, wenn man Cola und Bier trinkt? Man colabiert',
'Treffen sich zwei Magnete, sagt der eine: Was soll ich heute bloss anziehen?',
'War heute ohne Handy auf Toilette… Wir haben 167 Fliesen.',
'Hast du was zu trinken? Wasser. Nee, was Härteres! Ok, Eis.',
'Zu welchem Arzt geht Pinocchio? Zum Holz-Nasen-Ohren-Arzt',
'Was liegt am Strand und spricht undeutlich? Eine Nuschel',
'Was ist braun, klebt und läuft durch die Wüste? Ein Karamel',
'Was ist gross, grau und telefoniert? Ein Telefant',
'Was ist rot und steht im Wald? Ein Kirsch',
'Wie lautet der Vorname vom Reh? Kartoffelpü',
'Wie nennt man einen Bauern mit Studium? Ackerdemiker',
'Ein anderes Wort für iPhone-Hülle? Apfeltasche', 
'Was ist schwarz-weiss und sitzt auf der Schaukel? Ein Schwinguin',
'Was ist grün und guckt durch das Schlüsselloch? Ein Spionat',
'Was ist orange und läuft den Berg hoch? Eine Wanderrine',
'Was tragen Gummibären bei schlechtem Wetter? Gummistiefel',
'Welches Gemüse ist besonders lustig? Kichererbsen',
'Was bekommt ein Kannibale, der zu spät zum Essen kommt? Die kalte Schulter',
'Wie nennt man einen Keks, der unter einem Baum liegt? Ein schattiges Plätzchen',
'Wir haben uns für den Winter zwei Schneeschaufeln gekauft. Wir paarshippen jetzt.',
'Mein Zahnarzt sagt: Ich brauche eine Krone. Endlich sieht es jemand wie ich.',
'Was ist das Gegenteil von Frühlingserwachen? Spätrechtseinschlafen',
'Was ist grün, hat gute Laune und hüpft umher? Eine Freuschrecke',
'Wie nennt man einen Bumerang, der nicht zurückkommt? Einen Stock',
'Was ist weiss und rollt den Berg rauf? Eine Lawine mit Heimweh',
'Was trinken Führungskräfte? Leitungswasser',
'Welche Schuhe tragen Bild-Redakteure? Skandalen',
'Was macht ein Clown im Büro? Faxen',
'Wer schummelt im Dschungel? Mogli',
'Wie nennt man einen Spanier ohne Auto? Carlos',
'Wie nennt man den Flur im Iglu? Eisdiele',
'Wie nennt man einen Cowboy ohne Pferd? Einen Sattelschlepper',
'Warum ist Zucker schlauer als Salz? Weil er raffiniert ist',
'Was ist grün und steht vor der Tür? Ein Klopfsalat',
'Kopieren geht über studieren.',
'Lieber Buddha als Margarine.',
'Wer Ordnung hält, ist nur zu faul zum Suchen.',
'Jeder macht, was er will. Keiner macht, was er soll - aber all machen mit.',
'Komm raus und ergib dich – ich bin der Mehrzahl!',
'Wer Pech hat, hat schon vor der Prüfung Durchfall.',
'Lieber eine Stunde Schule als gar keinen Schlaf.',
'Lehrer sind unbestechlich, die meisten nehmen nicht mal Vernunft an.',
'Was ist der Unterschied zwischen einem alten Lehrer und einer alten Kaffeemaschine? Die Kaffeemaschine lässt sich noch entkalken!',
'Keine Atommülldeponie auf dem Mars! Denn Mars bringt verbrauchte Energie sofort zurück.',
'Theorie ist, wenn nichts klappt und jeder weiss, warum. Praxis ist, wenn alles klappt, und keiner weiss, warum. In diesem Raum sind Theorie und Praxis vereint: Nichts klappt und keiner weiss warum.',
'Das Gehirn ist eine fabelhafte Einrichtung! Es beginnt zu arbeiten, sobald man aufsteht, und es hört erst auf, wenn man in der Schule ankommt.',
'Es ist streng verboten, den Affen an der Tafel zu füttern.',
'Alle reden von ungewollten Kindern, von ungewollten Lehrern spricht niemand.',
'Das Gedächtnis ist wie eine Schublade, die ständig klemmt.',
'Lehrer: Was habe ich wenn ich in der einen Hand 3 Bierflaschen habe und in der anderen 6 Bierflaschen? Schüler: Ein Alkohol Problem. ',
'Was ist gefährlich? Niesen bei Durchfall.',
'Ein älteres Ehepaar sitzen zusammen im Restaurant. Auf einmal bekleckert sich die Frau mit Soße und sagt: „Oh nein, schau mal was für ein Rindvieh ich bin.” Da sagt der Mann: „Und bekleckert bist du auch noch.”',
'Eine schwangere Frau geht zum Metzger: "Ich bekomme 3 Kilo Gehacktes. Darauf der Metzger: "Sachen gibt es!"',
'Tochter: Mami, bin ich ein gewolltes Kind? Mutter: Das einzige, was ich wollte, war meine Schuhe zubinden.',
'Was ist das Weisse in Vogel-Kaka? Auch Vogel-Kaka.',
'Was ist das WICHTIGSTE bei einem Schweissausbruch? Der Buchstabe W',
'Win Mann geht in den Bächerladen, an der langen Warteschlange vorbei, haut den Kopf ein paar mal uf die Theke und sagt: "Ätsch, hab doch noch Hörnchen bekommen."',
'Patient: Herr Doktor, ich liege im Sterben! Doktor: Dann stehen Sie doch bitte auf.',
'Ich habe gerade eine Beziehung mit einer blinden Frau begonnen. Hab auch vorher lange geübt, bis ich die Stimme ihres Ehemannes hinbekam.',
'Hat mich tatsächlich so eine leicht bekleidete Dame am Bahnhof angesprochen. Sie meinte, für 30 Euro macht sie alles, was ich will. Jetzt rate mal, wer heute bei mir den Laminatboden verlegt.',
'Doktor: "Dicksein ist nicht gut für die Gesundheit. Sie sind zu dick." Mann: "Ich glaube, ich hole mir hier lieber eine zweite Meinung." Doktor: "Sie sind auch hässlich."',
'Schatz, ich habe Kopfschmerzen. Hast du etwas dagegen? Nein, das ist schon in Ordnung, dass du Kopfschmerzen hast.',
'Hans, was hast du dir nur dabei gedacht? Aber warum, Vögel auf eurer Hochzeit freizulassen ist doch romantisch. Ja Hans, aber doch nicht Strauße.',
'Warum sieht man Ameisen nicht in Kirchen? Weil sie in Sekten sind.',
'Was sagt ein Krokodil, das einen Clown gefressen hat? Schmeckt irgendwie komisch.',
'Wo wohnt eine Katze am liebsten? Im Miezhaus.',
'Kommt ein Pferd in die Bar. Fragt der Barkeeper: «Warum so ein langes Gesicht?»',
'Was kommt nach Elch? Zwölch.',
'Der Prinz angepisst - Rapunzel liess Harn herunter.',
'«Bitte 200 Gramm Leberwurst von der groben Fetten.» «Tut mir Leid, die hat heute Berufsschule.»',
'Was ist rot und schlecht für die Zähne? Ein Ziegelstein.',
'Kommt ein Buckliger zum Bäcker und sagt: «Ich hätte gern ein Brot.» Darauf sagt der Bäcker: «Schlucken Sie doch erstmal das alte runter.»',
'Was ist braun, klebrig und läuft durch die Wüste? Ein Karamel.',
'Was ist bunt und läuft über den Tisch davon? Ein Fluchtsalat!',
'Was ist grün, sauer und versteckt sich vor der Polizei? Ein Essig-Schurke.',
'Was ist weiss und stört beim Essen? Eine Lawine.',
'Was sagt man über einen Spanner, der gestorben ist? Der ist weg vom Fenster.',
'Geht ein Cowboy zum Coiffeur. Als er wieder rauskommt, ist sein Pony weg.',
'Treffen sich zwei Magneten. Sagt der eine: «Was soll ich heute bloss anziehen?»',
'Was essen Supermodels, wenns schnell gehen muss? Ein Laufsteak.',
'Was macht ein Pirat am Computer? Er drückt die Enter-Taste.',
'Was heisst Sonnenuntergang auf Finnisch? Helsinki.',
'«Hast du ein Bad genommen?» «Warum, fehlt eins?»',
'«Ich bin es leid, ständig hier herumzuhängen», sagte die Glühbirne und brannte durch.',
'Treffen sich zwei Voyeure. Fragt der eine: «Und was machst du heute noch so?» Sagt der andere: «Mal gucken.»',
'Wie heisst der chinesische Verkehrsminister? Um Lei Tung.',
'Kriegen sich zwei Glatzen in die Haare.',
'Was macht man mit einem Hund ohne Beine? Um die Häuser ziehen.',
'Zwei Bekloppte beissen in Eisenbahnschienen. Sagt der eine: «Boa, sind die hart!» Sagt der andere: «Geh doch da drüben hin, da ist ne Weiche!»',
'Wie heisst die Frau von Herkules? Frau Kules.',
'Kommt ein Einarmiger in einen Secondhandladen.',
'Was passiert, wenn man Cola und Bier gleichzeitig trinkt? Man colabiert.',
'Was findet man beim Kannibalen in der Dusche? Head and Shoulders.',
'Wie heisst ein Spanier ohne Auto? Carlos.',
'Warum trinken Mäuse keinen Alkohol? Weil sie Angst vom Kater haben.',
'Woraus wurde Jesus Haus gebaut? Aus Jerusa-Lehm.',
'Was lebt in der Savanne und ist immer sauber? Eine Hygiäne.',
'Wie nennt man einen dicken Schriftsteller? Kugelschreiber.',
'Warum können Skelette schlecht lügen? Weil sie leicht zu durchschauen sind.',
'Wie nennt man ein Rudel aggressiver Wölfe? Wolfgang.',
'Sagt der Pessimist: «Schlimmer gehts nicht!». Darauf der Optimist: «Doch!»',
'Ein Stein und ein Brett treffen aufeinander. Sagt der Stein «Ich bin ein Stein». Sagt das Brett: «Wenn du ein Stein bist, bin ich Brett Pitt.»',
'An der Zürcher Langstrasse wurde gestern ein Sarg gefunden. Man hat ihn aber nicht öffnen können. War wohl ein Zuhälter drin.',
'Alle Kinder spielen auf dem Spielplatz. Außer Mona - die hat Corona.',
'Alle Kinder gehen zur Hinrichtung. Ausser Inge, die hängt in der Schlinge.',
'Alle Mädchen wollen sein wie Brigit. Nur nicht Doris. Die will sein wie Boris.',
'Alle Kinder springen durch den Reifen. Nur nicht Nick. Der ist zu dick.',
'Alle Kinder essen Schnitzel. Nur nicht Sausanne, die liegt in der Pfanne.',
'Alle Kinder trinken Limo, nur nicht Nils, der säuft Pils.',
'Alle Kinder stoppen vorm Abgrund, nur nicht Peter, der geht noch nen Meter.',
'Alle Kinder nehmen Aspirin, außer Ali, der nimmt Zyankali!',
'Alle Kinder haben Haare. Nur nicht Torsten - der hat Borsten.',
'Alle Kinder besichtigen Löwen im Tierpark, nur nicht Jutta, die ist Futter.',
'"Der Gerichtsvollzieher hat sich gestern bei uns wie ein kleines Kind benommen." "Wieso denn das?" "Alles, was er sah, wollte er haben!"',
'Alle Kinder gehen über die Baustelle, nur nicht Jan, der hängt am Kran.',
'Alle Kinder tanzen um das Feuer, nur nicht Brigitte, die steht in der Mitte.',
'Allen Kindern schmeckt der Hamburger, nur nicht Jürgen, der muss würgen.',
'Alle Kinder schauen aufs brennende Haus, außer Klaus der schaut raus!',
'Alle Kinder spenden für Behinderte, nur nicht Anke, die sagt "Danke".',
'Alle Kinder essen Lasagne - außer Gerd der mag kein Pferd!',
'Alle Kinder sind gesund, nur nicht Jürgen, der muss würgen.',
'Alle Kinder fahren Eisenbahn. Nur nicht Sabine, die liegt auf der Schiene.',
'Alle Kinder decken den Tisch, nur nicht Jochen, den tun sie kochen.',
'Alle Kinder gehen über die Straße, nur nicht Jens, der klebt am Benz.',
'Alle Kinder haben eine Devise, nur nicht Otto, der hat ein Motto.',
'Allen Kindern steht das Wasser bis zum Hals, nur nicht Heiner, der ist nen Kopf kleiner.',
'Ein Melonenzüchter ärgert sich darüber, dass die Kinder aus der Nachbarschaft immer seine Melonen klauen.',
'Eines Tages wird es ihm zu bunt und er stellt ein Schild mit der Aufschrift: "Vorsicht! Eine der Melonen ist vergiftet" auf. Am Abend sieht er, wie die Kinder das Schild lesen und sofort wegrennen. Als er am nächsten Morgen nachsehen will, ob wirklich noch alle Melonen da sind, entdeckt er einen Zettel mit der Aufschrift: "Jetzt sind es zwei ..."',
'Alle Kinder gehen vom Friedhof, nur nicht Mark, der liegt im Sarg.',
'Alle Kinder essen Lasagne - außer Ronny, der mag kein Pony.',
'Alle Kinder essen Fleisch - außer Björn, der mag nur Möhren.',
'Alle Jungen ärgern gern Mädchen - nur nicht Agathe, die kann Karate.',
'Alle Kinder stoppen vorm Abgrund, nur nicht Peter, der geht noch nen Meter.',
'Zwei Ballons sind in der Wüste. Sagt der eine: „Vorsicht, ein Katkusssssssssss“'
]