# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: untrusted.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0funtrusted.proto\x12\tuntrusted\"\x17\n\x15GetCertificateRequest\"6\n\x13GetCertificateReply\x12\x1f\n\x17\x65nclave_tls_certificate\x18\x01 \x01(\x0c\"\x11\n\x0fGetTokenRequest\"\"\n GetSgxQuoteWithCollateralRequest\"\x1e\n\rGetTokenReply\x12\r\n\x05token\x18\x01 \x01(\t\"x\n\x1eGetSgxQuoteWithCollateralReply\x12\r\n\x05quote\x18\x01 \x01(\x0c\x12,\n\ncollateral\x18\x02 \x01(\x0b\x32\x18.untrusted.SgxCollateral\x12\x19\n\x11\x65nclave_held_data\x18\x03 \x01(\x0c\"\x80\x02\n\rSgxCollateral\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x1c\n\x14pck_crl_issuer_chain\x18\x02 \x01(\t\x12\x13\n\x0broot_ca_crl\x18\x03 \x01(\t\x12\x0f\n\x07pck_crl\x18\x04 \x01(\t\x12\x1d\n\x15tcb_info_issuer_chain\x18\x05 \x01(\t\x12\x10\n\x08tcb_info\x18\x06 \x01(\t\x12 \n\x18qe_identity_issuer_chain\x18\x07 \x01(\t\x12\x13\n\x0bqe_identity\x18\x08 \x01(\t\x12\x17\n\x0fpck_certificate\x18\t \x01(\t\x12\x19\n\x11pck_signing_chain\x18\n \x01(\t\"\x16\n\x14GetServerInfoRequest\"%\n\x12GetServerInfoReply\x12\x0f\n\x07version\x18\x01 \x01(\t2\xe9\x02\n\x0b\x41ttestation\x12R\n\x0eGetCertificate\x12 .untrusted.GetCertificateRequest\x1a\x1e.untrusted.GetCertificateReply\x12@\n\x08GetToken\x12\x1a.untrusted.GetTokenRequest\x1a\x18.untrusted.GetTokenReply\x12s\n\x19GetSgxQuoteWithCollateral\x12+.untrusted.GetSgxQuoteWithCollateralRequest\x1a).untrusted.GetSgxQuoteWithCollateralReply\x12O\n\rGetServerInfo\x12\x1f.untrusted.GetServerInfoRequest\x1a\x1d.untrusted.GetServerInfoReplyb\x06proto3')



_GETCERTIFICATEREQUEST = DESCRIPTOR.message_types_by_name['GetCertificateRequest']
_GETCERTIFICATEREPLY = DESCRIPTOR.message_types_by_name['GetCertificateReply']
_GETTOKENREQUEST = DESCRIPTOR.message_types_by_name['GetTokenRequest']
_GETSGXQUOTEWITHCOLLATERALREQUEST = DESCRIPTOR.message_types_by_name['GetSgxQuoteWithCollateralRequest']
_GETTOKENREPLY = DESCRIPTOR.message_types_by_name['GetTokenReply']
_GETSGXQUOTEWITHCOLLATERALREPLY = DESCRIPTOR.message_types_by_name['GetSgxQuoteWithCollateralReply']
_SGXCOLLATERAL = DESCRIPTOR.message_types_by_name['SgxCollateral']
_GETSERVERINFOREQUEST = DESCRIPTOR.message_types_by_name['GetServerInfoRequest']
_GETSERVERINFOREPLY = DESCRIPTOR.message_types_by_name['GetServerInfoReply']
GetCertificateRequest = _reflection.GeneratedProtocolMessageType('GetCertificateRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCERTIFICATEREQUEST,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.GetCertificateRequest)
  })
_sym_db.RegisterMessage(GetCertificateRequest)

GetCertificateReply = _reflection.GeneratedProtocolMessageType('GetCertificateReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCERTIFICATEREPLY,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.GetCertificateReply)
  })
_sym_db.RegisterMessage(GetCertificateReply)

GetTokenRequest = _reflection.GeneratedProtocolMessageType('GetTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTOKENREQUEST,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.GetTokenRequest)
  })
_sym_db.RegisterMessage(GetTokenRequest)

GetSgxQuoteWithCollateralRequest = _reflection.GeneratedProtocolMessageType('GetSgxQuoteWithCollateralRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSGXQUOTEWITHCOLLATERALREQUEST,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.GetSgxQuoteWithCollateralRequest)
  })
_sym_db.RegisterMessage(GetSgxQuoteWithCollateralRequest)

GetTokenReply = _reflection.GeneratedProtocolMessageType('GetTokenReply', (_message.Message,), {
  'DESCRIPTOR' : _GETTOKENREPLY,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.GetTokenReply)
  })
_sym_db.RegisterMessage(GetTokenReply)

GetSgxQuoteWithCollateralReply = _reflection.GeneratedProtocolMessageType('GetSgxQuoteWithCollateralReply', (_message.Message,), {
  'DESCRIPTOR' : _GETSGXQUOTEWITHCOLLATERALREPLY,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.GetSgxQuoteWithCollateralReply)
  })
_sym_db.RegisterMessage(GetSgxQuoteWithCollateralReply)

SgxCollateral = _reflection.GeneratedProtocolMessageType('SgxCollateral', (_message.Message,), {
  'DESCRIPTOR' : _SGXCOLLATERAL,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.SgxCollateral)
  })
_sym_db.RegisterMessage(SgxCollateral)

GetServerInfoRequest = _reflection.GeneratedProtocolMessageType('GetServerInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVERINFOREQUEST,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.GetServerInfoRequest)
  })
_sym_db.RegisterMessage(GetServerInfoRequest)

GetServerInfoReply = _reflection.GeneratedProtocolMessageType('GetServerInfoReply', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVERINFOREPLY,
  '__module__' : 'untrusted_pb2'
  # @@protoc_insertion_point(class_scope:untrusted.GetServerInfoReply)
  })
_sym_db.RegisterMessage(GetServerInfoReply)

_ATTESTATION = DESCRIPTOR.services_by_name['Attestation']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCERTIFICATEREQUEST._serialized_start=30
  _GETCERTIFICATEREQUEST._serialized_end=53
  _GETCERTIFICATEREPLY._serialized_start=55
  _GETCERTIFICATEREPLY._serialized_end=109
  _GETTOKENREQUEST._serialized_start=111
  _GETTOKENREQUEST._serialized_end=128
  _GETSGXQUOTEWITHCOLLATERALREQUEST._serialized_start=130
  _GETSGXQUOTEWITHCOLLATERALREQUEST._serialized_end=164
  _GETTOKENREPLY._serialized_start=166
  _GETTOKENREPLY._serialized_end=196
  _GETSGXQUOTEWITHCOLLATERALREPLY._serialized_start=198
  _GETSGXQUOTEWITHCOLLATERALREPLY._serialized_end=318
  _SGXCOLLATERAL._serialized_start=321
  _SGXCOLLATERAL._serialized_end=577
  _GETSERVERINFOREQUEST._serialized_start=579
  _GETSERVERINFOREQUEST._serialized_end=601
  _GETSERVERINFOREPLY._serialized_start=603
  _GETSERVERINFOREPLY._serialized_end=640
  _ATTESTATION._serialized_start=643
  _ATTESTATION._serialized_end=1004
# @@protoc_insertion_point(module_scope)
