
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-02T13:56:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "67657c1eecb22047f9eb4ae92bf0ab254a922892",
 "version": "2804"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
