# Generated by Django 4.1.2 on 2022-10-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnortRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.TextField(max_length=30)),
                ('template', models.TextField(max_length=30)),
                ('content', models.TextField(max_length=2048)),
                ('description', models.TextField(max_length=256)),
                ('extra', models.TextField(max_length=256)),
                ('location', models.TextField(max_length=256)),
                ('request_ref', models.TextField(max_length=12)),
                ('main_ref', models.TextField(max_length=12)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
