# Generated by Django 4.1.2 on 2022-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort', '0005_alter_snortrule_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snortrule',
            name='template',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='snortrule',
            name='type',
            field=models.TextField(choices=[('a', 'type a'), ('b', 'Preprocessor')], max_length=30),
        ),
    ]
