# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/util/elementary_types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2truera/protobuf/public/util/elementary_types.proto\"\x1b\n\tFloatList\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1d\n\x0bIntegerList\x12\x0e\n\x06values\x18\x01 \x03(\x03\"e\n\tValueList\x12\x1a\n\x06\x66loats\x18\x01 \x01(\x0b\x32\n.FloatList\x12\x1c\n\x07strings\x18\x02 \x01(\x0b\x32\x0b.StringList\x12\x1e\n\x08integers\x18\x03 \x01(\x0b\x32\x0c.IntegerListB2\n\x18\x63om.truera.protobuf.utilB\x14\x45lementaryTypesProtoP\x01\x62\x06proto3')



_FLOATLIST = DESCRIPTOR.message_types_by_name['FloatList']
_STRINGLIST = DESCRIPTOR.message_types_by_name['StringList']
_INTEGERLIST = DESCRIPTOR.message_types_by_name['IntegerList']
_VALUELIST = DESCRIPTOR.message_types_by_name['ValueList']
FloatList = _reflection.GeneratedProtocolMessageType('FloatList', (_message.Message,), {
  'DESCRIPTOR' : _FLOATLIST,
  '__module__' : 'truera.protobuf.public.util.elementary_types_pb2'
  # @@protoc_insertion_point(class_scope:FloatList)
  })
_sym_db.RegisterMessage(FloatList)

StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLIST,
  '__module__' : 'truera.protobuf.public.util.elementary_types_pb2'
  # @@protoc_insertion_point(class_scope:StringList)
  })
_sym_db.RegisterMessage(StringList)

IntegerList = _reflection.GeneratedProtocolMessageType('IntegerList', (_message.Message,), {
  'DESCRIPTOR' : _INTEGERLIST,
  '__module__' : 'truera.protobuf.public.util.elementary_types_pb2'
  # @@protoc_insertion_point(class_scope:IntegerList)
  })
_sym_db.RegisterMessage(IntegerList)

ValueList = _reflection.GeneratedProtocolMessageType('ValueList', (_message.Message,), {
  'DESCRIPTOR' : _VALUELIST,
  '__module__' : 'truera.protobuf.public.util.elementary_types_pb2'
  # @@protoc_insertion_point(class_scope:ValueList)
  })
_sym_db.RegisterMessage(ValueList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.truera.protobuf.utilB\024ElementaryTypesProtoP\001'
  _FLOATLIST._serialized_start=54
  _FLOATLIST._serialized_end=81
  _STRINGLIST._serialized_start=83
  _STRINGLIST._serialized_end=111
  _INTEGERLIST._serialized_start=113
  _INTEGERLIST._serialized_end=142
  _VALUELIST._serialized_start=144
  _VALUELIST._serialized_end=245
# @@protoc_insertion_point(module_scope)
