MISSING_RTI_OPTIONS = 'missing rti options'
MISSING_WSGI_APP = 'wsgi app'
MISSING_API_KEY = 'missing api_key'
MISSING_TAG_HASH = 'tag_hash'
MISSING_API_ENDPOINT = 'api endpoint is missing or invalid'
INVALID_URI_EXCLUSION_LIST = 'invalid uri_exclusion should be a list of regex or strings'
INVALID_THREAT_CODE_LIST = 'invalid_block_redirect_codes and invalid_captcha_codes must be list of integers'
DUPLICATE_THREAT_CODE = 'threat type in invalid_block_redirect_codes and invalid_captcha_codes must be uniq for each list'
