
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-01T11:54:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "01f3bb4b6df1576d6057ed232935a4ac075246e8",
 "version": "2.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
