
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-02T20:44:41+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "a6e52c79008e1108388e8ae3b236f4915cf0248e",
 "version": "0.5.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
