
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-02T14:33:24+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a32c62c20d9f769d4ffef3bce9a19efc3c88557",
 "version": "2.10.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
