
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T19:28:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a440beb6025a4ac4ff5762ef9fe3caf39cbee47d",
 "version": "1.0.12.post.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
