
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T16:58:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e17b976e810ac54340db47377a3c0c3a75147aaa",
 "version": "0.4.162"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
