
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-01T22:57:16-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c322478e3caaa81a7ad22c4294d33c66a1471f33",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
