

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sum_columns(object):
    def setupUi(self, sum_columns):
        sum_columns.setObjectName("sum_columns")
        sum_columns.resize(866, 380)
        self.label = QtWidgets.QLabel(sum_columns)
        self.label.setGeometry(QtCore.QRect(150, 40, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.col_new_position = QtWidgets.QLineEdit(sum_columns)
        self.col_new_position.setGeometry(QtCore.QRect(600, 100, 113, 22))
        self.col_new_position.setObjectName("lineEdit")
        self.new_col_name = QtWidgets.QLineEdit(sum_columns)
        self.new_col_name.setGeometry(QtCore.QRect(600, 140, 113, 22))
        self.new_col_name.setObjectName("lineEdit_2")
        self.first_col_to_sum = QtWidgets.QLineEdit(sum_columns)
        self.first_col_to_sum.setGeometry(QtCore.QRect(600, 180, 113, 22))
        self.first_col_to_sum.setObjectName("lineEdit_3")
        self.second_col_to_sum = QtWidgets.QLineEdit(sum_columns)
        self.second_col_to_sum.setGeometry(QtCore.QRect(600, 230, 113, 22))
        self.second_col_to_sum.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(sum_columns)
        self.label_2.setGeometry(QtCore.QRect(150, 100, 401, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(sum_columns)
        self.label_3.setGeometry(QtCore.QRect(150, 140, 401, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(sum_columns)
        self.label_4.setGeometry(QtCore.QRect(150, 180, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(sum_columns)
        self.label_5.setGeometry(QtCore.QRect(150, 220, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.sum_col_btn = QtWidgets.QPushButton(sum_columns)
        self.sum_col_btn.setGeometry(QtCore.QRect(350, 300, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sum_col_btn.setFont(font)
        self.sum_col_btn.setObjectName("pushButton")

        self.retranslateUi(sum_columns)
        QtCore.QMetaObject.connectSlotsByName(sum_columns)

    def retranslateUi(self, sum_columns):
        _translate = QtCore.QCoreApplication.translate
        sum_columns.setWindowTitle(_translate("sum_columns", "Sum up two columns"))
        self.label.setText(_translate("sum_columns", "Sum  two columns and show results on a newly created column"))
        self.label_2.setText(_translate("sum_columns", "Where do you want the new column to bea added?"))
        self.label_3.setText(_translate("sum_columns", "Enter the name of new column"))
        self.label_4.setText(_translate("sum_columns", "Enter the name of the FIRST column to sum up"))
        self.label_5.setText(_translate("sum_columns", "Enter the name of the SECOND  column to sum up"))
        self.sum_col_btn.setText(_translate("sum_columns", "Sum columns"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sum_columns = QtWidgets.QDialog()
    ui = Ui_sum_columns()
    ui.setupUi(sum_columns)
    sum_columns.show()
    sys.exit(app.exec_())
