
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T17:23:34-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b608042492c0da4c91112f612f51824208b08cf9",
 "version": "v0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
