from rdflib import Namespace

# A few common ones
BP = Namespace("http://www.biopax.org/release/biopax-level3.owl#")
RDF = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
RDFS = Namespace("http://www.w3.org/2000/01/rdf-schema#")
OWL = Namespace("http://www.w3.org/2002/07/owl#")
XSD = Namespace("http://www.w3.org/2001/XMLSchema#")
SKOS = Namespace("http://www.w3.org/TR/skos-reference/")
DC = Namespace("http://purl.org/dc/elements/1.1/")
VOID = Namespace("http://rdfs.org/ns/void#")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
SD = Namespace("http://www.w3.org/ns/sparql-service-description#")

# Identifiers.org ones
idATC      = Namespace("http://identifiers.org/atc/")
idBindingDB = Namespace("http://identifiers.org/bindingDB/")
idChEBI    = Namespace("http://identifiers.org/chebi/")
idChEMBLCompound   = Namespace("http://identifiers.org/chembl.compound/")
idChEMBLTarget = Namespace("http://identifiers.org/chembl.target/")
idDbSnp    = Namespace("http://identifiers.org/dbsnp/")
idDrugBank = Namespace("http://identifiers.org/drugbank/")
idEC       = Namespace("http://identifiers.org/ec-code/")
idEnsembl  = Namespace("http://identifiers.org/ensembl/")
idEnsemblMetazoa = Namespace("http://identifiers.org/ensembl.metazoa/")
idEnsemblFungi = Namespace("http://identifiers.org/ensembl.fungi/")
idEnsemblBacteria = Namespace("http://identifiers.org/ensembl.bacteria/")
idEnsemblPlant = Namespace("http://identifiers.org/ensembl.plant/")
idEnsemblProtist = Namespace("http://identifiers.org/ensembl.protist/")
idFlybase  = Namespace("http://identifiers.org/flybase/")
idGO       = Namespace("http://identifiers.org/go/")
idHap      = Namespace("http://identifiers.org/hapmap/")
idHgncSymbol = Namespace("http://identifiers.org/hgnc.symbol/")
idInsdc    = Namespace("http://identifiers.org/insdc/")
idKEGG     = Namespace("http://identifiers.org/kegg.drug/")
idPdb      = Namespace("http://identifiers.org/pdb/")
idPubchemCompound = Namespace("http://identifiers.org/pubchem.compound/")
idPubchemSubstance = Namespace("http://identifiers.org/pubchem.substance/")
idPubmed   = Namespace("http://identifiers.org/pubmed/")
idRefseq   = Namespace("http://identifiers.org/refseq/")
idSiderDrug = Namespace("http://identifiers.org/sider.drug/")
idSiderEffect = Namespace ("http://identifiers.org/sider.effect/")
idStitch    = Namespace("http://identifiers.org/stitch/")
idTaxonomy = Namespace("http://identifiers.org/taxonomy/")
idUniprot  = Namespace("http://identifiers.org/uniprot/")
idWormbase = Namespace("http://identifiers.org/wormbase/")

# identifying Project data namespaces

GBID_CPSD_ORG = Namespace("http://generalbioinformatics.com/identifiers/cpsd/organism/")
GBID_CPSD_PEP = Namespace("http://generalbioinformatics.com/identifiers/cpsd/peptide/")
GBID_CPSD_GENE = Namespace("http://generalbioinformatics.com/identifiers/cpsd/gene/")
GBID_CPSD_TRANS = Namespace("http://generalbioinformatics.com/identifiers/cpsd/transcript/")
GBID_CPSD_VERSION = Namespace("http://generalbioinformatics.com/identifiers/cpsd/version/")
GBID_MOA_TARGET = Namespace("http://generalbioinformatics.com/identifiers/moa/target/")
