# Generated by Django 3.2.5 on 2021-07-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_cashnet', '0006_auto_20201104_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
