# Generated by Django 3.2.14 on 2022-07-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_cashnet', '0007_auto_20210723_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cashnet_error_message',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cashnet_result_message',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='internal_error_message',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
