
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T16:54:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "820a222070a6814c8a2a584e6fde4599f9ab84ec",
 "version": "0.4.161"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
