
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-05T17:43:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e10a10500777cf09b7d6a36aedb3c29fb4bbdd02",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
