
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-01T12:44:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cba36555044aa2e6cb92c2d9e770d79089a6f1f4",
 "version": "2022.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
