
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-01T11:06:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "afc3ee44d57c2f86a20d9db74c649dc99f0d6136",
 "version": "0.7.1.post.dev802"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
