
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-09T10:31:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1e1cfd190a4722b9b298443d26481b95c40cacc",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
