
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T16:26:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "625acb80c0a78b7d37a0ee469313fd8ec42df8aa",
 "version": "1.0.0.rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
