
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-01T09:54:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0f546d54657357c6c31d86a4671c7052be53fa5",
 "version": "1.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
