"""
# About the RubberDoc Package

This package contains all of the code which generated these reference docs!  

The page you see here was generated by the \__init__.py file for this package. 
In the configuration file it is set to rename \__init__.py files to 'index'. 
Feel free to update the configuration file to set other aliases that are project specific.  

Happy Documenting!
"""
__version__ = '0.2.8'
