#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2204-101-g0a8bef49"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2204
#define NETGEN_VERSION_TWEAK 101
#define NETGEN_VERSION_HASH "g0a8bef49"
#endif // NETGEN_VERSION_HPP_INCLUDED
