stages = {
    '1-1-N': dict(
        nodes = [(0,0),(1,0),(2,0)],
        index_node_start = 0,
        index_node_boss = 2,
        indices_node_mobs = [1],
        boss_caution = False,
        mobs_caution = [False],
        index_node_box = -1,
    ),
    '1-2-N': dict(
        nodes = [(0,0),(1,0),(0,1),(1,1)],
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [2],
        boss_caution = False,
        mobs_caution = [False],
        index_node_box = -1,
    ),
    '1-3-N': dict(
        nodes = [(0,0),(0,1),(1,1),(-1,2)],
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [2],
        boss_caution = False,
        mobs_caution = [True],
        index_node_box = -1,
    ),
    '1-4-N': dict(
        nodes = [(0,0),(0,1),(-1,2),(1,1),(2,1)],
        index_node_start = 0,
        index_node_boss = 4,
        indices_node_mobs = [2],
        boss_caution = True,
        mobs_caution = [True],
        index_node_box = -1,
    ),
    '1-5-N': dict(
        nodes = [(0,0),(1,0),(1,-1),(2,-1),(3,-1)],
        index_node_start = 0,
        index_node_boss = 4,
        indices_node_mobs = [1,2],
        boss_caution = True,
        mobs_caution = [True,False],
        index_node_box = -1,
    ),
    '1-1-H': dict(
        nodes = [(0,0),(1,0),(2,0),(1,1),(2,1)],
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [1],
        boss_caution = False,
        mobs_caution = [False],
        index_node_box = 4,
    ),
    '1-2-H': dict(
        nodes = [(0,0),(0,1),(1,1),(0,2),(-1,2)],
        index_node_start = 0,
        index_node_boss = 4,
        indices_node_mobs = [2],
        boss_caution = False,
        mobs_caution = [True],
        index_node_box = 3,
    ),
    '1-3-H': dict(
        nodes = [(0,0),(1,0),(-1,1),(0,1),(1,1),(0,2)],
        index_node_start = 0,
        index_node_boss = 4,
        indices_node_mobs = [1,3],
        boss_caution = False,
        mobs_caution = [True,True],
        index_node_box = 2,
    ),
    '2-1-N': dict(
        nodes = [(0,0),(1,-1),(2,-1),(3,-1),(2,-2)],
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [1,4],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, False],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '2-2-N': dict(
        nodes = [(0,0),(1,0),(1,-1),(2,-1),(3,-1)],
        index_node_start = 0,
        index_node_boss = 4,
        indices_node_mobs = [2,3],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [True, False],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '2-3-N': dict(
        nodes = [(0,0),(1,-1),(2,-1),(2,0),(3,-2)],
        index_node_start = 0,
        index_node_boss = 4,
        indices_node_mobs = [1,3],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [True, True],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '2-4-N': dict(
        nodes = [(0,0),(1,-1),(2,-1),(2,0),(2,-2)],
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [1,4],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [False, False],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '2-5-N': dict(
        nodes = [(0,0),(1,-1),(2,-1),(2,0),(3,0),(3,-2)],
        index_node_start = 0,
        index_node_boss = 5,
        indices_node_mobs = [1,4],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [False, False],
        mobs_dash = [False, True],
        index_node_box = -1,
    ),
    '2-1-H': dict(
        nodes = [(0,0),(1,0),(1,1),(2,1),(1,2),(2,2),(0,3)],
        index_node_start = 0,
        index_node_boss = 6,
        indices_node_mobs = [2,5],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
        index_node_box = 3,
        index_node_light = 1,
    ),
    '2-2-H': dict(
        nodes = [(0,0),(1,-1),(2,-2),(3,-2),(3,-3),(4,-3),(3,-1),(2,0),(1,1)],
        index_node_start = 0,
        index_node_boss = 8,
        indices_node_mobs = [2,4],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
        index_node_box = 5,
        index_node_light = 1,
    ),
    '2-3-H': dict(
        nodes = [(0,0),(1,0),(2,0),(1,-1),(2,-1),(3,-1),(4,-1),(2,1),(1,2),(0,2)],
        index_node_start = 0,
        index_node_boss = 9,
        indices_node_mobs = [3,5],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [True, True],
        mobs_dash = [False, False],
        index_node_box = 6,
        index_node_light = 1,
    ),
    '3-1-N': dict(
        nodes = [(0,0),(1,0),(2,0),(4,0),(0,1),(1,1),(3,0)],
        nodes_not_shown = [6],
        nodes_generator = {2: 6},
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [1,4],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, False],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '3-2-N': dict(
        nodes = [(0,0),(1,0),(0,1),(1,1),(2,1),(3,0),(3,1)],
        nodes_not_shown = [3],
        nodes_generator = {2: 3},
        index_node_start = 0,
        index_node_boss = 6,
        indices_node_mobs = [1,5],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [True, True],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '3-3-N': dict(
        nodes = [(0,0),(1,0),(2,-1),(3,-1),(3,0),(3,-2),(4,-3)],
        nodes_not_shown = [5],
        nodes_generator = {2: 5},
        index_node_start = 0,
        index_node_boss = 6,
        indices_node_mobs = [1,4],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [False, False],
        mobs_dash = [False, True],
        index_node_box = -1,
    ),
    '3-4-N': dict(
        nodes = [(0,0),(3,0),(4,0),(0,1),(1,1),(2,1),(3,1),(1,2),(3,2)],
        nodes_not_shown = [5,6], # [4,6],
        nodes_generator = {3: 6, 4: 5}, # {1: 6, 2: 4},
        index_node_start = 0,
        index_node_boss = 8,
        indices_node_mobs = [7,2], # [3,7],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, False],
        mobs_dash = [True, True],
        index_node_box = -1,
    ),
    '3-5-N': dict(
        nodes = [(0,0),(1,0),(-2,-1),(-1,-1),(0,-1),(0,-2),(0,-3),(0,-4),(1,-4)],
        nodes_not_shown = [5,6],
        nodes_generator = {3: 5, 4: 6},
        index_node_start = 0,
        index_node_boss = 8,
        indices_node_mobs = [1,2],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [False, True],
        mobs_dash = [True, False],
        index_node_box = -1,
    ),
    '3-1-H': dict(
        nodes = [(0,0),(1,0),(0,1),(2,0),(3,0),(2,1),(3,1),(4,0),(5,-1)],
        nodes_not_shown = [3,7],
        nodes_generator = {1: 3, 4: 7},
        index_node_start = 0,
        index_node_boss = 8,
        indices_node_mobs = [2,5],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [True, True],
        mobs_dash = [False, False],
        index_node_box = 6,
    ),
    '3-2-H': dict(
        nodes = [(0,0),(0,1),(2,1),(-2,2),(-1,2),(0,2),(1,2),(2,2),(0,3),(2,3),(3,3),(-1,4),(-2,4)],
        nodes_not_shown = [6],
        nodes_generator = {5:6},
        index_node_start = 0,
        index_node_boss = 10,
        indices_node_mobs = [3,12],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [False, False],
        mobs_dash = [True, True],
        index_node_box = 2,
        index_node_light = 1,
    ),
    '3-3-H': dict(
        nodes = [(0,0),(1,0),(2,-1),(2,-2),(1,-2),(1,-3),(3,-2),(4,-2),(4,-3),(5,-2),(6,-2),(6,-1)],
        nodes_not_shown = [9,10],
        nodes_generator = {2:10, 7:9},
        index_node_start = 0,
        index_node_boss = 11,
        indices_node_mobs = [5,8],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [False, True],
        mobs_dash = [True, False],
        index_node_box = 6,
        index_node_light = 1,
    ),
    '4-1-N': dict(
        nodes = [(0,0),(1,0),(3,0),(4,0),(3,1),(4,1)],
        nodes_portal = {1:2},
        index_node_start = 0,
        index_node_boss = 5,
        indices_node_mobs = [3,4],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '4-2-N': dict(
        nodes = [(0,0),(0,1),(1,1),(2,0),(3,0),(3,-1),(4,-1)],
        nodes_portal = {1:5},
        index_node_start = 0,
        index_node_boss = 6,
        indices_node_mobs = [3,4],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [True, False],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '4-3-N': dict(
        nodes = [(0,0),(0,1),(1,1),(2,0),(2,2),(3,2)],
        nodes_portal = {1:4, 4:1},
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [2,5],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '4-4-N': dict(
        nodes = [(0,0),(1,0),(2,0),(3,0),(3,-1),(1,2),(2,2)],
        nodes_portal = {2:6, 6:2},
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [1,4],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
        index_node_box = -1,
    ),
    '4-5-N': dict(
        nodes = [(0,0),(1,0),(2,0),(-1,1),(-1,2),(0,2),(-2,2),(-2,3)],
        nodes_portal = {1:5},
        index_node_start = 0,
        index_node_boss = 6,
        indices_node_mobs = [2,7],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [True, False],
        mobs_dash = [False, True],
        index_node_box = -1,
    ),
    '4-1-H': dict(
        nodes = [(0,0),(1,0),(2,0),(3,0),(3,-1),(2,1),(3,1),(2,2),(1,2),(0,2)],
        nodes_portal = {1:8},
        index_node_start = 0,
        index_node_boss = 4,
        indices_node_mobs = [2,9],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
        index_node_box = 3,
        index_node_light = 7,
    ),
    '4-2-H': dict(
        nodes = [(0,0),(1,-1),(0,1),(1,1),(2,1),(3,-1),(3,0),(3,1),(2,2)],
        nodes_portal = {1:3},
        index_node_start = 0,
        index_node_boss = 8,
        indices_node_mobs = [2,5],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [True, False],
        mobs_dash = [False, True],
        index_node_box = 7,
    ),
    '4-3-H': dict(
        nodes = [(0,0),(1,0),(0,1),(2,1),(1,2),(0,3),(-1,3),(1,-1),(1,-2),(2,-2)],
        nodes_portal = {7:4, 4:7},
        index_node_start = 0,
        index_node_boss = 6,
        indices_node_mobs = [3,8],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [True, False],
        mobs_dash = [False, False],
        index_node_box = 9,
    ),
    '5-1-N': dict(
        nodes = [(0,0),(1,-1),(1,-2),(2,-2),(3,-2),(3,-3)],
        nodes_annihilation = {1:2},
        index_node_start = 0,
        index_node_boss = 4,
        indices_node_mobs = [3,5],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
    ),
    '5-2-N': dict(
        nodes = [(0,0),(1,0),(2,0),(3,0),(0,1),(1,1)],
        nodes_annihilation = {1:5},
        index_node_start = 0,
        index_node_boss = 3,
        indices_node_mobs = [2,4],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
    ),
    '5-3-N': dict(
        nodes = [(0,0),(1,-1),(2,-2),(3,-2),(2,-1),(2,0)],
        nodes_annihilation = {4:3},
        index_node_start = 0,
        index_node_boss = 5,
        indices_node_mobs = [1,2,3],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [False, True, True],
        mobs_dash = [False, False, False],
    ),
    '5-4-N': dict(
        nodes = [(0,0),(0,1),(1,1),(2,0),(3,0),(2,-1),(1,2),(2,2)],
        nodes_annihilation = {2:6},
        index_node_start = 0,
        index_node_boss = 5,
        indices_node_mobs = [1,4,7],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True, False],
        mobs_dash = [False, False, True],
    ),
    '5-5-N': dict(
        nodes = [(0,0),(1,0),(2,0),(2,1),(3,1),(2,-1),(3,-1),(4,-1),(3,-2),(4,-2)],
        nodes_annihilation = {6:2},
        index_node_start = 0,
        index_node_boss = 9,
        indices_node_mobs = [5,4,7],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [False, False, True],
        mobs_dash = [False, True, False],
    ),
    '5-1-H': dict(
        nodes = [(0,0),(1,0),(2,0),(3,0),(1,1),(2,1),(3,1),(2,-1),(3,-1),(4,-1)],
        nodes_annihilation = {4:8},
        index_node_start = 0,
        index_node_boss = 6,
        indices_node_mobs = [7,3],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True],
        mobs_dash = [False, False],
        index_node_box = 8,
        index_node_light = 1,
    ),
    '5-2-H': dict(
        nodes = [(0,0),(1,0),(1,1),(2,1),(2,2),(3,0),(4,0),(2,-1),(3,-1),(4,-2)],
        nodes_annihilation = {7:3, 2:8},
        index_node_start = 0,
        index_node_boss = 6,
        indices_node_mobs = [4,5,9],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, False, True],
        mobs_dash = [False, False, False],
        index_node_box = 8,
        index_node_light = 1,
    ),
    '5-3-H': dict(
        nodes = [(0,0),(1,-1),(2,-1),(2,0),(3,0),(2,-2),(3,-2),(4,-2),(2,-3),(4,-3),(5,-4)],
        nodes_annihilation = {2:3, 5:8},
        index_node_start = 0,
        index_node_boss = 10,
        indices_node_mobs = [4,8,6,9],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True, False, False],
        mobs_dash = [True, False, False, False],
        index_node_box = 7,
        index_node_light = 1,
    ),
    '6-1-N': dict(
        nodes = [(0,0),(1,0),(2,0),(2,1),(2,2),(2,3),(-1,3),(0,2),(1,2)],
        nodes_generator = {1:8},
        index_node_start = [0,6],
        index_node_boss = 5,
        indices_node_mobs = [3,4,7],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [True, False, False],
        mobs_dash = [False, False, False],
    ),
    '6-2-N': dict(
        nodes = [(0,0),(1,0),(2,0),(2,-1),(2,-2),(3,-2),(2,-3),(4,-1),(5,-2),(4,-2)],
        nodes_generator = {2:9},
        index_node_start = [0,6],
        index_node_boss = 8,
        indices_node_mobs = [3,4,7],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [True, False, True],
        mobs_dash = [False, False, False],
    ),
    '6-3-N': dict(
        nodes = [(0,0),(1,0),(1,-1),(2,-1),(1,-2),(2,-3),(3,-3),(3,-4),(3,-2),(4,-2),(5,-2)],
        nodes_generator = {2:8, 3:9},
        index_node_start = [0,7],
        index_node_boss = 10,
        indices_node_mobs = [4,5,6],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [True, True, False],
        mobs_dash = [False, False, False],
    ),
    '6-4-N': dict(
        nodes = [(0,0),(1,0),(1,1),(1,-1),(2,-1),(2,-2),(3,-2),(4,-2),(5,-2)],
        nodes_generator = {4:7},
        index_node_start = [0,2],
        index_node_boss = 8,
        indices_node_mobs = [1,5,6],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True, False],
        mobs_dash = [False, False, False],
    ),
    '6-5-N': dict(
        nodes = [(0,0),(0,-1),(0,-2),(0,-3),(0,-4),(1,-5),(2,-1),(1,-2),(2,-2),(2,-3),(3,-4),(4,-4),(3,-5)],
        nodes_generator = {8:1,7:9},
        index_node_start = [0,6],
        index_node_boss = 11,
        indices_node_mobs = [2,5,10,12],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [False, False, False, True],
        mobs_dash = [False, True, False, False],
    ),
    '6-1-H': dict(
        nodes = [(0,0),(1,-1),(2,-1),(2,0),(3,-1),(2,-2),(2,-3),(3,-3),(1,-3),(0,-2),(1,-4)],
        nodes_generator = {6:2},
        index_node_start = [0,9],
        index_node_boss = 4,
        indices_node_mobs = [5,7,10],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [True, True, True],
        mobs_dash = [False, False, False],
        index_node_box = 3,
        index_node_light = 1,
    ),
    '6-2-H': dict(
        nodes = [(0,0),(2,0),(0,-1),(1,-1),(2,-1),
                 (3,-1),(0,-2),(2,-2),(3,-2),(1,-3),
                 (2,-3),(3,-3)],
        nodes_generator = {2:8, 10:4},
        index_node_start = [0,6],
        index_node_boss = 1,
        indices_node_mobs = [7,9,11],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, False, True],
        mobs_dash = [False, False, False],
        index_node_box = 5,
        index_node_light = 3,
    ),
    '6-3-H': dict(
        nodes = [(0,0),(1,0),(1,-1),(-1,-1),(-1,-2),
                 (0,-2),(1,-2),(2,-2),(0,-3),(1,-3),
                 (2,-3),(3,-3)],
        nodes_generator = {10:9,2:5},
        index_node_start = [0,11],
        index_node_boss = 3,
        indices_node_mobs = [4,6,7],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [True, False, True],
        mobs_dash = [False, False, False],
        index_node_box = 8,
    ),
    '7-1-N': dict(
        nodes = [(0,0),(1,0),(1,-1),(1,-2),(2,-2),
                 (3,0),(4,0),(5,0),(6,-1),(6,-2),
                 (4,-2),(5,-3)],
        nodes_portal = {1:10, 10:1, 4:5},
        index_node_start = [0,3],
        index_node_boss = 9,
        indices_node_mobs = [6,7,11],
        boss_caution = False,
        boss_dash = True,
        mobs_caution = [False, False, False],
        mobs_dash = [False, False, False],
    ),
    '7-2-N': dict(
        nodes = [(0,0),(0,-1),(1,-1),(2,-1),(4,-2),
                 (5,-2),(3,-3),(4,-3),(5,-3)],
        nodes_portal = {3:4},
        index_node_start = [0,1],
        index_node_boss = 6,
        indices_node_mobs = [2,5,8],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, True, True],
        mobs_dash = [False, False, False],
    ),
    '7-3-N': dict(
        nodes = [(0,0),(1,-1),(1,-2),(0,-2),(-1,-1),
                 (1,1),(2,0),(3,-1)],
        nodes_portal = {1:6, 6:1},
        index_node_start = [0,7],
        index_node_boss = 4,
        indices_node_mobs = [2,3,5],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, False, True],
        mobs_dash = [False, False, False],
    ),
    '7-4-N': dict(
        nodes = [(0,0),(1,0),(2,0),(1,-1),(2,-1),
                 (3,-1),(1,2),(2,2),(3,1),(4,1),
                 (2,3),(4,2)],
        nodes_portal = {1:6, 5:8, 8:5},
        index_node_start = [0,3],
        index_node_boss = 11,
        indices_node_mobs = [2,4,7,10],
        boss_caution = True,
        boss_dash = False,
        mobs_caution = [False, False, False, True],
        mobs_dash = [False, False, False, False],
    ),
    
    '8-2-N': dict(
        nodes = [(0,0),(1,0),(-1,1),(0,1),(0,2),
                 (2,1),(1,2),(-2,3),(-3,3),(-3,2),
                 (-3,4)],
        nodes_portal = {2:9},
        nodes_generator = {7:6},
        index_node_start = [0,1],
        index_node_boss = 5,
        indices_node_mobs = [3,8,10],
        boss_caution = False,
        boss_dash = False,
        mobs_caution = [False, False, False],
        mobs_dash = [False, False, False],
    ),
}
