
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-05T17:06:27-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6648e44f514b7429aa99dac85b958d763ff80f1",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
