# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

# WDG_HW_TASK = task and hardware watchdog activated (default)
# WDG_HW = hardware watchdog acivated; don't care about task watchdog
# WDG_NONE = neither task or hardware watchdog is needed
# WDG_DEFAULT = don't care about neither task or hardware watchdog, use of default value
class CallableWdgConfig(object):
    WDG_HW_TASK = 0
    WDG_HW = 1
    WDG_NONE = 2
    WDG_DEFAULT = 3

