
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T11:26:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c68b54709b7a4c11a644cb4f8e56c606944617d9",
 "version": "v0.26.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
