# Generated by Django 4.0.8 on 2022-12-04 16:05

from django.db import migrations, models
import django.db.models.deletion
import django_site.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='sites.site', verbose_name='Site')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=django_site.models.image_directory_path, verbose_name='Favicon of site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=django_site.models.image_directory_path, verbose_name='Logo of site')),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to=django_site.models.image_directory_path, verbose_name='Dark Logo of site')),
                ('small_logo', models.ImageField(blank=True, null=True, upload_to=django_site.models.image_directory_path, verbose_name='Small Logo of site')),
                ('mobile_logo', models.ImageField(blank=True, null=True, upload_to=django_site.models.image_directory_path, verbose_name='Mobile logo of site')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Configs',
                'db_table': 'django_site_config',
            },
        ),
    ]
